NumPy - Numerical Python

#Importing Numpy as NP

In [ ]:
#Importing numpy

import numpy as np

#List vs Numpy

In [ ]:
from time import process_time

In [ ]:
#Time taken by a list

python_list =[i for i in range(10000)]
start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.001549211999999578


In [ ]:
#Time taken by a Numpy Array

np_array = np.array([i for i in range(10000)])
start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0009631599999995188


#Creating Numpy array


In [ ]:
#1-D Array

np_array = np.array([51,20,100,108,101])
print(np_array)
print(type(np_array))

print(np_array.shape)

[ 51  20 100 108 101]
<class 'numpy.ndarray'>
(5,)


In [ ]:
#2-D Array

np_array1 =np.array([(1,2,3,4),(5,6,7,8)])
print(np_array1)
print(type(np_array1))
np_array1.shape

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


(2, 4)

In [ ]:
#Mentioning Datatype

np_array2 = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(np_array2)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [ ]:
#Initial Placeholders in numpy array (Numpy array with all values 0)

a = np.zeros((4,4),dtype = int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
#Numpy array with all the values as 1

b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Numpy array of a particular value

c = np.full((5,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#Creating Identity matrix

d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Numpy Array with random values

e = np.random.random((3,4))
print(e)

[[0.93871001 0.11182358 0.21734829 0.94257336]
 [0.1082086  0.49345805 0.40207444 0.93460259]
 [0.0533144  0.03949675 0.61155345 0.44487317]]


In [ ]:
#Numpy Array with random integers

f = np.random.randint(10,100,(3,5))
print(f)

[[70 14 13 71 35]
 [87 86 56 78 88]
 [93 25 37 51 69]]


In [ ]:
#Creating Array of evenly spaced values

g = np.linspace(10,30,11)
print(g)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [ ]:
#Creating Array of evenly spaced value  --> Specifying Step

h = np.arange(10,30,5)
print(h)

[10 15 20 25]


In [ ]:
#Converting list to Numpy array

list2 = [51,20,30,37,34]
print(list2)
print(type(list2))
np_array3 = np.array(list2)
print(np_array3)
print(type(np_array3))

[51, 20, 30, 37, 34]
<class 'list'>
[51 20 30 37 34]
<class 'numpy.ndarray'>


#Analyzing Numpy Array

In [ ]:
c = np.random.randint(20,51,(5,5))
print(c)

[[41 43 22 42 44]
 [27 40 31 27 47]
 [20 22 34 21 25]
 [36 32 50 38 45]
 [25 40 33 43 35]]


In [ ]:
#Dimension of Numpy array

print(c.ndim)

2


In [ ]:
#Number of elements in an array

print(c.size)

25


In [ ]:
#Checking the Datatype of values in the array

print(c.dtype)

int64


#Mathematical Operations on Numpy Array


In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # Concatenates or Join two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
#Mathematical Operations using +,-,*,/ Opeartors

np_array4 = np.random.randint(10,20,(3,3))
np_array5 = np.random.randint(0,10,(3,3))
print(np_array4)
print(-np_array5)
print(np_array4 + np_array5)
print(np_array4 - np_array5)
print(np_array4 * np_array5)
print(np_array4 / np_array5)

[[15 17 11]
 [18 19 10]
 [10 18 12]]
[[-1 -1 -3]
 [-7 -4  0]
 [-7 -7 -5]]
[[16 18 14]
 [25 23 10]
 [17 25 17]]
[[14 16  8]
 [11 15 10]
 [ 3 11  7]]
[[ 15  17  33]
 [126  76   0]
 [ 70 126  60]]
[[15.         17.          3.66666667]
 [ 2.57142857  4.75               inf]
 [ 1.42857143  2.57142857  2.4       ]]


<ipython-input-61-edb936299af9>:8: RuntimeWarning: divide by zero encountered in divide
  print(np_array4 / np_array5)


In [ ]:
#Mathematical Operations using add, subtract, multiply, divide method

np_array6 = np.random.randint(10,20,(3,3))
np_array7 = np.random.randint(0,10,(3,3))
print(np_array6)
print(np_array7)
print(np.add(np_array6,np_array7))
print(np.subtract(np_array6,np_array7))
print(np.multiply(np_array6,np_array7))
print(np.divide(np_array6,np_array7))


[[12 16 10]
 [17 13 11]
 [11 18 18]]
[[1 7 1]
 [8 4 2]
 [4 5 4]]
[[13 23 11]
 [25 17 13]
 [15 23 22]]
[[11  9  9]
 [ 9  9  9]
 [ 7 13 14]]
[[ 12 112  10]
 [136  52  22]
 [ 44  90  72]]
[[12.          2.28571429 10.        ]
 [ 2.125       3.25        5.5       ]
 [ 2.75        3.6         4.5       ]]


#Array Manipulations

In [ ]:
array_1 = np.random.randint(10,20,(2,3))
print(array_1)
print(array_1.shape)

[[15 19 14]
 [10 12 17]]
(2, 3)


In [ ]:
#Transpose of an array

trans = np.transpose(array_1)
print(trans)
print(trans.shape)

[[15 10]
 [19 12]
 [14 17]]
(3, 2)


In [ ]:
#Another method to transpose an array

trans_2 = array_1.T
print(trans_2)
print(trans_2.shape)


[[15 10]
 [19 12]
 [14 17]]
(3, 2)


In [ ]:
#Reshaping an Array

array_2 = np.random.randint(30,52,(2,3))
print(array_2)
print(array_2.shape)

reshaped_array = array_2.reshape(3,2)
print(reshaped_array)
print(reshaped_array.shape)

[[32 48 36]
 [40 40 31]]
(2, 3)
[[32 48]
 [36 40]
 [40 31]]
(3, 2)
